name: "Dependency review for new vulns"

on:
  pull_request:
    branches: [ develop, master ]

permissions:
  contents: read

jobs:
  dependency_scan:
    runs-on: self-hosted 
    name: Scan source code for vulnerable dependencies
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v1