name: "Dependency review and create issue"

on:
  [pull_request, push]

permissions:
  contents: read

jobs:
  dependency_scan:
    runs-on: self-hosted 
    name: Scan source code for vulnerable dependencies
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v1
      - name: Dependabot issue for PRs
        if: always()
        uses: goatandsheep/dependabot-issue-action@v1.0.1