name: GitHub Security Alerts for Jira

on: [push]

jobs:
  syncSecurityAlerts:
    runs-on: self-hosted
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.x
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_HOST: ${{ secrets.JIRA_HOST }}
          JIRA_USER: dorest28@gmail.com
          JIRA_PROJECT: Tetropinks
          JIRA_ISSUE_TYPE: Security
          JIRA_WATCHERS: dorest28@gmail.com