name: "ZAP Full Scan"

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]

jobs:
  zap_scan:
    runs-on: self-hosted 
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://10.0.4.240:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -d -g full-alerts.conf -r full-report_html.html -J full-report_json.json'
          fail_action: true
      - name: Copy ZAP files
        if: always()
        run: |
          echo "Moving configuration file to results folder"
          mkdir -p results
          echo "Current directory is:"
          pwd
          cp full-alerts.conf results/full-alerts.conf
          cp full-report_json.json results/full-report_json.json
          cp full-report_html.html results/full-report_html.html