name: "ZAP API Scan"

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]

jobs:
  zap_scan:
    runs-on: self-hosted 
    name: Scan API of Juice Shop instance on Heroku
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: 'http://owasp-juice-shop-228.herokuapp.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'