name: "ZAP API Scan"

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: self-hosted 
    name: Scan API of Juice Shop instance on Heroku
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: 'http://owasp-juice-shop-228.herokuapp.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -d' # -S runs scan in safe mode
      - name: Copy ZAP files
        run: |
          echo "Moving configuration file to results folder"
          mkdir -p results
          echo "Current directory is:"
          pwd
          cp alerts.conf results/api-alerts.conf
          cp report_json.json results/api-report_json.json
          cp report_html.html results/api-report_html.html