name: "ZAP API Scan"

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: self-hosted 
    name: Scan API of Juice Shop instance on Heroku
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
      
      - name: Create var for ZAP Auth
        run: |
          export ZAP_AUTH_TOKEN=${{secrets.ZAP_AUTH_TOKEN}}
          
      # Scan first API endpoint
      - name: ZAP Scan Profile Management API
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: '.zap/Profile_Management_API.mock.rev1.yaml'
          rules_file_name: '.zap/api_rules-test.tsv'
          allow_issue_writing: true
          fail_action: false
          cmd_options: '-a -d -r report_html.html -z "-configfile .zap/options.prop"'
      - name: Copy ZAP files 1
        run: |
          echo "Moving configuration file to results folder"
          mkdir -p results
          echo "Current directory is:"
          pwd
          cp report_html.html results/m1-report_html.html

      # Scan second API endpoint
      - name: ZAP Scan Case Management API
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: '.zap/Case_Management_API.yaml'
          rules_file_name: '.zap/api_rules-test.tsv'
          allow_issue_writing: true
          fail_action: false
          cmd_options: '-a -d -r report_html.html -z "-configfile .zap/options.prop"'
      - name: Copy ZAP files 2
        run: |
          echo "Moving configuration file to results folder"
          mkdir -p results
          echo "Current directory is:"
          pwd
          cp report_html.html results/m2-report_html.html