name: "ZAP API Scan"

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]

jobs:
  zap_scan:
    runs-on: self-hosted 
    name: Scan API of Juice Shop instance on Heroku
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: 'http://owasp-juice-shop-228.herokuapp.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -d -S -g alerts.conf -r report_html.html -J report_json.json' # -S runs scan in safe mode
      - name: Copy ZAP files
        run: |
          echo "Moving configuration file to results folder"
          mkdir -p $HOME/opt/github-actions-runners/juice-shop/_work/juice-shop/results
          cp alerts.conf results/alerts.conf
          cp report_json.json results/report_json.json
          cp report_html.html results/report_html.html