name: "ZAP API Scan"

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: self-hosted 
    name: Scan API of Juice Shop instance on Heroku
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: '.zap/openapi_v1.json'
          rules_file_name: '.zap/api_rules-test.tsv'
          allow_issue_writing: true
          fail_action: false
          cmd_options: '-a -d -r report_html.html' # -S runs scan in safe mode
      - name: Copy ZAP files
        run: |
          echo "Moving configuration file to results folder"
          mkdir -p results
          echo "Current directory is:"
          pwd
          cp report_html.html results/au-report_html-3rules.html