name: "ZAP Docker Scan"

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]

jobs:
  zap_scan:
    runs-on: self-hosted 
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - name: Check out Git repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #v2: v2.3.4 available
        with:
          ref: develop
      - name: ZAP Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py \
          -t http://owasp-juice-shop-228.herokuapp.com -x report_xml.xml
      - name: Move ZAP report to zap dir
        run: |
          mkdir zap
          cp zap/wrk/report_xml.xml zap/
          ls zap/
      - name: Publish report to DefectDojo
        id: import-scan
        uses: ivanamat/defectdojo-import-scan@v1
        with:
          token: ${{ secrets.DEFECTOJO_TOKEN }}
          defectdojo_url: ${{ secrets.DEFECTOJO_URL }}
          file: zap/report_json.json
          scan_type: ZAP Scan
          engagement: 1
      - name: Show response
        run: |
          set -e
          printf '%s\n' '${{ steps.import-scan.outputs.response }}'
